apiVersion: apps/v1
kind: Deployment
metadata:
  name: gh-runner-${RUNNER_ID}
  namespace: ${OPENSHIFT_NAMESPACE}
spec:
  selector:
    matchLabels:
      app: gh-runner-${RUNNER_ID}
  replicas: 1
  template:
    metadata:
      labels:
        app: gh-runner-${RUNNER_ID}
    spec:
      containers:
        - name: gh-runner-${RUNNER_ID}
          image: >-
            image-registry.apps.silver.devops.gov.bc.ca/${OPENSHIFT_NAMESPACE}/gh-runner-ubuntu-18:latest
          env:
            - name: REPO
              value: ${GITHUB_REPO}
            - name: ORGANIZATION
              value: bcgov
            - name: ACCESS_TOKEN
              value: ${GITHUB_ACCESS_TOKEN}
