---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: quickstart-network-security-policy
metadata:
  name: quickstart-network-security-policy
objects:
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: deny-by-default
    spec:
      # The default posture for a security first namespace is to
      # deny all traffic. If not added this rule will be added
      # by Platform Services during environment cut-over.
      podSelector: {}
      ingress: []
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
    spec:
      # This policy allows any pod with a route & service combination
      # to accept traffic from the OpenShift router pods. This is
      # required for things outside of OpenShift (like the Internet)
      # to reach your pods.
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      podSelector: {}
      policyTypes:
        - Ingress
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: allow-same-namespace
    spec:
      # Allow all pods within the current namespace to communicate
      # to one another.
      podSelector:
      ingress:
        - from:
            - podSelector: {}
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: allow-traffic-from-gateway-to-penmyed-api
    spec:
      podSelector:
        matchLabels:
          app: pen-myed-api-main
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  environment: test
                  name: 264e6f
        - from:
            - namespaceSelector:
                matchLabels:
                  environment: prod
                  name: 264e6f
  - kind: NetworkPolicy
    apiVersion: networking.k8s.io/v1
    metadata:
      name: allow-common-to-pen
    spec:
      # Allow all pods from the given namespace to talk to
      # the services deployed in PEN Namespace.
      podSelector: { }
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  environment: ${ENVIRONMENT}
                  name: ${COMMON_NAMESPACE_PREFIX}
              podSelector: { }
parameters:
  - name: NAMESPACE_PREFIX
    displayName: Namespace
    description: |
      The namespace prefix this policy is being deployed to;
    required: true
  - name: COMMON_NAMESPACE_PREFIX
    displayName: Common Namespace
    description: |
      The namespace prefix this policy is being deployed to;
    required: true
  - name: ENVIRONMENT
    displayName: Namespace
    description: |
      The namespace prefix this policy is being deployed to;
    required: true
