pipeline {
  agent any

  environment {
    DEBUG_OUTPUT = 'false'

    TOOLS = 'c2mvws-tools'
    DEV = 'c2mvws-dev'
    TEST = 'c2mvws-test'
    PROD = 'c2mvws-prod'

    REPO_NAME = 'educ-infra-common'
    OWNER = 'bcgov'
    JOB_NAME = 'master'

    APP_NAME = 'maintenance-page'
    APP_DOMAIN = 'pathfinder.gov.bc.ca'

    SOURCE_REPO_RAW = 'https://github.com/${OWNER}/${REPO_NAME}/master'
    SOURCE_REPO_REF = 'feature/maintenance-page'
    SOURCE_REPO_URL = 'https://github.com/${OWNER}/${REPO_NAME}.git'

    TOOLS_HOST_ROUTE = "${APP_NAME}-${TOOLS}.${APP_DOMAIN}"
    DEV_HOST_ROUTE = "${APP_NAME}-${DEV}.${APP_DOMAIN}"
    TEST_HOST_ROUTE = "${APP_NAME}-${TEST}.${APP_DOMAIN}"
    PROD_HOST_ROUTE = "${APP_NAME}-${PROD}.${APP_DOMAIN}"
  }

  stages {
    stage('Initialize') {
      steps {
        script {
          if (DEBUG_OUTPUT.equalsIgnoreCase('true')) {
            // Force OpenShift Plugin directives to be verbose
            openshift.logLevel(1)

            // Print all environment variables
            echo 'DEBUG - All pipeline environment variables:'
            echo sh(returnStdout: true, script: 'env')
          }
        }
      }
    }
    stage('Build') {
      steps {
        script {
          openshift.withCluster() {
            openshift.withProject(TOOLS) {
              Backend: {
                try {
                  echo "Building backend..."
                  def bcBackend = openshift.process('-f', 'maintenance-page/openshift/bc.yaml', "REPO_NAME=${REPO_NAME}", "JOB_NAME=${JOB_NAME}", "SOURCE_REPO_URL=${SOURCE_REPO_URL}", "SOURCE_REPO_REF=${SOURCE_REPO_REF}")
                  openshift.apply(bcBackend).narrow('bc').startBuild('-w').logs('-f')

                  openshift.tag("${REPO_NAME}-backend:latest", "${REPO_NAME}-backend:${JOB_NAME}")
                } catch (e) {
                  echo "Backend build failed"
                  throw e
                }
              }
            }
          }
        }
      }
      post {
        success {
          echo 'Cleanup BuildConfigs...'
          script {
            openshift.withCluster() {
              openshift.withProject(TOOLS) {
                if (DEBUG_OUTPUT.equalsIgnoreCase('true')) {
                  echo "DEBUG - Using project: ${openshift.project()}"
                } else {
                  def bcBackend = openshift.selector('bc', "${REPO_NAME}-backend-${JOB_NAME}")

                  if (bcBackend.exists()) {
                    echo "Removing BuildConfig ${REPO_NAME}-backend-${JOB_NAME}..."
                    bcBackend.delete()
                  }
                }
              }
            }
          }
        }
        failure {
          echo 'Build stage failed'
        }
      }
    }
    stage('Deploy to Dev') {
      steps {
        deployStage('Dev', (String)DEV)
      }
      post {
        success {
          echo 'Deployment to Dev was successful'
        }
        failure {
          echo 'Deployment to Dev failed'
        }
      }
    }
    /*stage('e2e tests') {
      agent {
        node {
          label 'nodejs10'
        }
      }
      steps {
        script {
          timeout(10) {
            dir('frontend') {
              echo 'Running e2e tests'
              sh 'npm install'
              sh 'npm run test:e2e'
            }
          }
        }
      }
    }*/
  }
}

def deployStage(String stageEnv, String projectEnv) {
  if (!stageEnv.equalsIgnoreCase('Dev')) {
    input("Deploy to ${projectEnv}?")
  }

  openshift.withCluster() {
    openshift.withProject(projectEnv) {
      if (DEBUG_OUTPUT.equalsIgnoreCase('true')) {
        echo "DEBUG - Using project: ${openshift.project()}"
      }
      echo "Tagging Image ${NAME}..."
      openshift.tag("${TOOLS}/${NAME}", "${NAME}")

      echo "Processing DeploymentConfig ${REPO_NAME}-backend..."
      def dcBackendTemplate = openshift.process('-f',
              'maintenance-page/openshift/dc.yaml',
              "NAME=${NAME}"
      )

      def dcBackend = openshift.apply(dcBackendTemplate).narrow('dc')

      // Wait for deployments to roll out
      timeout(10) {
        Backend: {
          dcBackend.rollout().status('--watch=true')
        }
      }
    }
  }
}
