---
apiVersion: v1
kind: Template
labels: 
  template: pen-request-e2e-pipeline-template
metadata: 
  name: pen-request-e2e-pipeline-template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata: 
    name: "pen-request-e2e-master-pipeline"
  spec:
    source:
      git:
        ref: master
        uri: "https://github.com/bcgov/EDUC-PEN-REQUEST"
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: tools/jenkins/e2e-Jenkinsfile
