---
apiVersion: template.openshift.io/v1
kind: Template
labels: 
  template: pen-request-email-api-pipeline
metadata: 
  name: pen-request-email-api-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata: 
    name: "pen-request-email-api-pipeline"
  spec:
    source:
      git:
        uri: "https://github.com/bcgov/EDUC-PEN-REQUEST-EMAIL-API"
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: tools/Jenkins/Jenkinsfile
