---
apiVersion: v1
kind: Template
labels: 
  template: pen-request-api-pipeline
metadata: 
  name: pen-request-api-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata: 
    name: "pen-request-api-pipeline"
  spec:
    source:
      git:
        uri: "https://github.com/bcgov/EDUC-PEN-REQUEST-API"
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: tools/Jenkins/Jenkinsfile
