---
apiVersion: v1
kind: Template
labels: 
  template: test-pipeline
metadata: 
  name: test-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata: 
    name: "test-pipeline"
  spec:
    source:
      git:
        ref: master
        uri: "https://github.com/bcgov/EDUC-INFRA-COMMON"
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: openshift/pipelines/test-pipeline/Jenkinsfile-test
