---
apiVersion: v1
kind: Template
labels:
  template: 'api-base-spring-boot-2.3.2-template'
metadata:
  name: 'api-base-spring-boot-2.3.2-template-bc'
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      creationTimestamp:
      labels:
        build: "api-base-spring-boot-2.3.2-template"
      name: "api-base-spring-boot-2.3.2-template"
    spec:
      lookupPolicy:
        local: false
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewBuild
      creationTimestamp:
      labels:
        build: "api-base-spring-boot-2.3.2-template"
      name: "api-base-spring-boot-2.3.2-template"
    spec:
      completionDeadlineSeconds: 1200
      successfulBuildsHistoryLimit: 3
      failedBuildsHistoryLimit: 3
      nodeSelector:
      output:
        to:
          kind: ImageStreamTag
          name: "educ-spring-boot-2.3.2-template:latest"
      postCommit: {}
      resources:
        requests:
          cpu: 100m
          memory: 2Gi
        limits:
          cpu: 1000m
          memory: 4Gi
        runPolicy: SerialLatestOnly
      source:
        cotextDir: openshift/spring-boot/2.3.2
        git:
          ref: "master"
          uri: "https://github.com/bcgov/educ-infra-common.git"
        type: Git
      strategy:
        dockerStrategy:
          env:
            - name: BUILD_LOGLEVEL
              value: '2'
        type: Docker
parameters:
  - name: REPO_NAME
    description: Application repository name
    required: true
  - name: JOB_NAME
    description: Job identifier (i.e. 'pr-5' OR 'master')
    required: true
  - name: SOURCE_REPO_REF
    description: Git Pull Request Reference (i.e. 'pull/CHANGE_ID/head')
    required: true
  - name: SOURCE_REPO_URL
    description: Git Repository URL
    required: true
