apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: NAMESPACE
  - name: COMMON_NAMESPACE
  - name: ENVIRONMENT
objects:
  - apiVersion: security.devops.gov.bc.ca/v1alpha1
    kind: NetworkSecurityPolicy
    metadata:
      name: egress-internet
    spec:
      description: "allow ${NAMESPACE}-${ENVIRONMENT} namespace to talk to the internet."
      source:
        - - $namespace=${NAMESPACE}-${ENVIRONMENT}
      destination:
        - - ext:network=any
  - apiVersion: security.devops.gov.bc.ca/v1alpha1
    kind: NetworkSecurityPolicy
    metadata:
      name: intra-namespace-comms
    spec:
      description: "allow ${NAMESPACE}-${ENVIRONMENT} namespace to talk to itself"
      source:
        - - $namespace=${NAMESPACE}-${ENVIRONMENT}
      destination:
        - - $namespace=${NAMESPACE}-${ENVIRONMENT}
  - apiVersion: security.devops.gov.bc.ca/v1alpha1
    kind: NetworkSecurityPolicy
    metadata:
      name: int-cluster-k8s-api-comms
    spec:
      description: "allow ${NAMESPACE} pods to talk to the k8s api"
      destination:
        - - int:network=internal-cluster-api-endpoint
      source:
        - - $namespace=${NAMESPACE}-${ENVIRONMENT}
  - apiVersion: security.devops.gov.bc.ca/v1alpha1
    kind: NetworkSecurityPolicy
    metadata:
      name: intra-namespace-comms-dev
    spec:
      description: "allow ${NAMESPACE}-${ENVIRONMENT} pods to talk to ${COMMON_NAMESPACE}-${ENVIRONMENT} pods"
      destination:
        - - $namespace=${COMMON_NAMESPACE}-${ENVIRONMENT}
      source:
        - - $namespace=${NAMESPACE}-${ENVIRONMENT}
  - apiVersion: security.devops.gov.bc.ca/v1alpha1
    kind: NetworkSecurityPolicy
    metadata:
      name: intra-namespace-comms-tools
    spec:
      description: "allow ${NAMESPACE}-${ENVIRONMENT} pods to talk to ${NAMESPACE}-tools for images"
      destination:
        - - $namespace=${NAMESPACE}-tools
      source:
        - - $namespace=${NAMESPACE}-${ENVIRONMENT}