---
apiVersion: v1
kind: Template
labels: 
  template: dev-pipeline
metadata: 
  name: dev-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata: 
    name: "dev-pipeline"
  spec:
    source:
      git:
        ref: master
        uri: "https://github.com/bcgov/EDUC-INFRA-COMMON"
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: openshift/pipelines/dev-pipeline/Jenkinsfile-dev
