create index STUDENT.PEN_RETRIEVAL_REQUEST_PEN_RETRIEVAL_REQUEST_STATUS_CODE_IDX on STUDENT.PEN_RETRIEVAL_REQUEST ( PEN_RETRIEVAL_REQUEST_STATUS_CODE );
create index STUDENT.PEN_RETRIEVAL_REQUEST_PEN_IDX on STUDENT.PEN_RETRIEVAL_REQUEST ( PEN );
create index STUDENT.PEN_RETRIEVAL_REQUEST_LEGAL_LAST_NAME_IDX on STUDENT.PEN_RETRIEVAL_REQUEST ( LEGAL_LAST_NAME );
create index STUDENT.PEN_RETRIEVAL_REQUEST_LEGAL_FIRST_NAME_IDX on STUDENT.PEN_RETRIEVAL_REQUEST ( LEGAL_FIRST_NAME );
create index STUDENT.PEN_RETRIEVAL_REQUEST_REVIEWER_IDX on STUDENT.PEN_RETRIEVAL_REQUEST ( REVIEWER );
create index STUDENT.PEN_RETRIEVAL_REQUEST_INITIAL_SUBMIT_DATE_IDX on STUDENT.PEN_RETRIEVAL_REQUEST ( INITIAL_SUBMIT_DATE );