---
apiVersion: v1
kind: Template
labels: 
  template: prod-pipeline
metadata: 
  name: prod-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata: 
    name: "prod-pipeline"
  spec:
    source:
      git:
        ref: master
        uri: "https://github.com/bcgov/EDUC-INFRA-COMMON"
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: openshift/pipelines/prod-pipeline/Jenkinsfile-prod
