kind: Template
apiVersion: v1
labels:
  app: jenkins-custom
metadata:
  name: jenkins-custom-template
objects:
  - apiVersion: v1
    kind: BuildConfig
    labels:
      app: jenkins-custom
    metadata:
      name: jenkins-custom-build
    spec:
      source:
        git:
          uri: https://github.com/bcgov/EDUC-INFRA-COMMON
          ref: "feature/jenkins-build"
        contextDir: openshift/jenkins
        type: Git
      strategy:
        dockerStrategy:
          from:
            kind: ImageStreamTag
            name: jenkins-basic:latest
            namespace: bcgov
        type: Docker
      output:
        to:
          kind: ImageStreamTag
          name: jenkins:latest
  - apiVersion: v1
    kind: ImageStream
    labels:
      app: jenkins-custom
    metadata:
      name: jenkins
      namespace: c2mvws-dev
