kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: clamav-deploy
parameters:
  - name: NAME_SPACE
    value: 75e61b-tools
    required: true
  - name: CPU_REQUEST
    value: "100m"
  - name: CPU_LIMIT
    value: "1100m"
  - name: MEMORY_REQUEST
    value: "500M"
  - name: MEMORY_LIMIT
    value: "2G"
  - name: REPLICAS
    value: "1"
  - name: TAG
    description: tag identifier for the image
    required: true
  - name: IMAGE_NAME
    description: name for the clamav image
    value: "clamav"
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      name: clamav
      labels:
        app: clamav
    spec:
      ports:
        - name: 3310-tcp
          protocol: TCP
          port: 3310
          targetPort: 3310
      selector:
        deploymentconfig: clamav
      type: ClusterIP
      sessionAffinity: None
    status:
      loadBalancer: {}

  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      name: clamav
      generation: 1
      creationTimestamp: null
      labels:
        app: clamav
    spec:
      strategy:
        type: Rolling
        activeDeadlineSeconds: 21600
      triggers:
        - type: ConfigChange
      replicas: ${{REPLICAS}}
      test: false
      selector:
        app: clamav
        deploymentconfig: clamav
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: clamav
            deploymentconfig: clamav
          annotations:
            openshift.io/generated-by: OpenShiftWebConsole
        spec:
          containers:
            - resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
              readinessProbe:
                tcpSocket:
                  port: 3310
                initialDelaySeconds: 240
                timeoutSeconds: 3
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              terminationMessagePath: /dev/termination-log
              name: clamav
              livenessProbe:
                tcpSocket:
                  port: 3310
                initialDelaySeconds: 240
                timeoutSeconds: 3
                periodSeconds: 10
                successThreshold: 1
                failureThreshold: 3
              ports:
                - containerPort: 3310
                  protocol: TCP
              terminationMessagePolicy: File
            - image: image-registry.openshift-image-registry.svc:5000/${NAME_SPACE}/${IMAGE_NAME}:${TAG}
              name: clamav
              imagePullPolicy: Always
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
