kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "scan-master-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/bcgov/EDUC-INFRA-COMMON"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: zap-scan/JenkinsfileMaster